FROM python:3.11-slim

WORKDIR /app
COPY streamlit_app.py .
COPY requirements.frontend.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.frontend.txt

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
