version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: booking-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/credentials.json:/app/app/credentials.json

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: booking-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_HOST=http://backend:8000
