FROM python:3.11-slim

WORKDIR /app
COPY ./app .
COPY requirements.backend.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.backend.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
