FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y git
RUN pip install --no-cache-dir -r requirements.txt
CMD ["bash", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 & streamlit run streamlit_app.py --server.port 8501"]